# Generated by Django 3.2.8 on 2021-10-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
